### ISSUE TITLE
output to json?

### ISSUE THREAD

**Issue by johndpope** [dan-nadler/ParseyAPI#2]
when I fire up my docker container using this file
https://gist.github.com/johndpope/5772af264aa1495ed2a5a192019513e1

I can see the output from console using this 
http://0.0.0.0:8000/parse/getParse?text=to%20be%20or%20not%20to%20be%20that%20is%20the%20question

but trying to pass output_type=csv - 💩 blows up.

http://0.0.0.0:8000/parse/getParse?text=to%20be%20or%20not%20to%20be%20that%20is%20the%20question&output_type=csv

<img width="1164" alt="screen shot 2016-10-09 at 20 22 10" src="https://cloud.githubusercontent.com/assets/289994/19224933/ffde5fac-8e5d-11e6-9b7d-685b02194c80.png">

I'm thinking this isn't quite what I had in mind. 

Need to get this parsey_api project working and circle back to this django front end.
They updated the core libraries to expose protocol buffers.
https://gist.githubusercontent.com/johndpope/fc1c2327a4ae255d9c44dda9b67b5288/raw/5b0923fd2565cd86a6d76c09ddc563fc53959447/parseyapi.sh

**Comment by dan-nadler** [comment]
I'm assuming that's  because the CSV option uses a different sh file, though the error message wouldn't suggest that that's the problem. Did you create a file 'syntaxnet/my_demo.sh' that outputs the results from syntaxnet as CSV?

 On that note, you can point the API to any sh file you like in by creating a new 'if' statement here: https://github.com/dan-nadler/ParseyAPI/blob/master/API/views.py

**Comment by johndpope** [comment]
thanks for getting back to me Dan
fyi - found this https://github.com/JoshData/parsey-mcparseface-server/
I still want to use protobufs that way I can hook up some swift server side code to talk to it.
